name: Continous Deployment

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: CI Action
        uses: ./.github/workflows/CI.yml
        steps:
        - name: Deploy to Clojars
          needs: build
          uses: jlesquembre/clojars-publish-action@0.3
          env:
            CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
            CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
