name: Continous Integration

on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
          node-version: 18

    - name: Setup Emacs
      uses: purcell/setup-emacs@master
      with:
        version: snapshot

    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@10.1
      with:
        cli: 1.10.1.693
        clj-kondo: 2022.05.31

    - name: Check emacs version
      run: emacs --version

    - name: Check emacs path
      run: emacs -Q --batch --eval '(message "%s" default-directory)' 

    - name: Tangle
      run: |
        time emacs -Q --batch
                   --eval '(load-file \".github\workflows\init.el\")'   \
                   --eval '(org-babel-lob-ingest \"Setup.org\")'        \
                   --eval '(org-sbe helpers)'                           \
                   --eval '(org-babel-tangle-file \"index.org\")'
    
    - name: Build
      run: |
        npm i
        clojure -M:build
    
    - name: Run tests
      run: 'clojure -M:test'

    - name: Package for Clojars
      run: 'clojure -M:jar'
